version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
      - ../data:/app/data
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=development
      - PYTHONPATH=/app
    command: flask run --host=0.0.0.0

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend 